### ISSUE TITLE
Application cannot be run

### ISSUE THREAD

**Issue by strepon** [RonakRah/shiny_app#3]
When starting the application from scratch, the following error occurs:
```
Error in mutate(., State = tolower(stateName)) : 
  object 'arrData' not found
```

**Comment by RonakRah** [comment]
Thank you for your feedback. the problem was with the name of the variable the data was assigned to and it is fixed.

**Comment by strepon** [comment]
Confirmed, now the application starts well.

(To follow the workflow, you can close this issue now as it is resolved.)
